env: 
  global: 
  - GH_REPO="myplanetdigital/swat"
    secure: "NbEOpsLT3HLJWluLDSb9/9XBeDgEuW6HJpjX2SzHpochuegJCSgsSckUay8CB2VLBzPoWyZbo/ImEBpuA8TP2XyS7pPW+l2/O6bcd+sI+xqUw7fztoKDq4yDEBOYAKCsPUVtK6GXRk9CCEJ/wxpdRvdO2eMjfc8xWjEcJwUocpA="
language: node_js
script: 
  - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then docpad deploy-ghpages --env static; fi
branches: 
  only: 
    - master
before_script: 
- npm install -g grunt-cli
- grunt
- ./prebuild.sh
