env: 
  global: 
  - GH_REPO="myplanetdigital/swat"
  - secure: JlqokOuz2JPPe9dwUzvhkN+qQbHdamtIMloCyzBKr3k1Nqw16Z3Qm9Pwgr9XE9cU6SyCTU/KEEu4pYHEEJP0AaXXPU/yQzd1Zix8L9bqTF22MoD2qdBQ4ttjXMKS9E17+QpVmEYjAjwIGNyTQch7q/rs2ZXzt6dGv3pgJu/rH9M=
node_js: "0.10"
language: node_js
script: 
  - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then docpad deploy-ghpages --env static
branches: 
  only: 
    - master
before_script: 
- npm install -g grunt-cli
- grunt
- ./prebuild.sh
